package domain.commands;

public enum CommandName {
  GIVE_TREE,
  GIVE_MI_FILE,
  TAKE_FILE_FROM_SERVER,
  TAKE_TREE,
  CONNECT_OK,
  SERVER_FILE_ACCEPTED,
  CLIENT_FILE_ACCEPTED,
  BEGIN_FILE_SAVE,
  DELETE_FILE,
  SERVER_FILE_DELETE_OK,
  SERVER_FILE_DELETE_NO,
  LOGIN,
  LOGIN_OK,
  BAD_PASS

}
